### ISSUE TITLE
iFrame testing?

### ISSUE THREAD

**Issue by jtayler** [covener/apache-samesite#3]
My iFrame test from a local 127.0.0.0: web service pops up an iFrame to my hosted web service that is using Apache and these rules. 

The cookies are stripped on the iFrame but I can see them normally in an open window or if I turn off Chrome's SameSite option.

What could be wrong?

**Comment by covener** [comment]
I suggest logging %{User-Agent}i , %{Set-Cookie}o and %{SAMESITE_SKIP}e with and without the configuration included.

**Comment by jtayler** [comment]
Do I understand, including 

%{User-Agent}i , %{Set-Cookie}o and %{SAMESITE_SKIP}e

as an apache directive in my .conf somewhere will cause output logs in httpd output?

**Comment by covener** [comment]
yes something like:
```
CustomLog logs/cookie-debug.log "%h %l %u %t \"%r\" %>s %b %{User-Agent}i SC=\"%{Set-Cookie}o\" SKIP=%{SAMESITE_SKIP}e"
```

**Comment by jtayler** [comment]
Indeed, this leaves a cookie-debug.log 

Hitting the server reports odd results. Firstly, I see ZERO cookies come though the iFrame. 

In this output I can see three related cookies each marked path=/; SameSite=None; Secure, but NOT the login cookie that I normally see along with these other three cookies. 

I didn't see reason to copy the output of the logs but I can if that helps.

I've also moved the originating site into a domain with SSL incase there were secure issues.

![image](https://user-images.githubusercontent.com/1004984/102029413-61bdcd80-3d7c-11eb-8070-28224fb16339.png)

If that image works, you can see all expected cookies make it down to the browser and seem to be marked secure although the "-" in the SameSite column I only THINK stands for None?

**Comment by jtayler** [comment]
I also note these other cookies are a chat service that also appears when I use the Chrome extension to turn off SameSite, oddly they are not marked secure -- these cookies are equally blocked. Does  that suggest the problem is somehow in the way we're presenting the iFrame or the SSL of the originating site?

**Comment by jtayler** [comment]
This seems to be reported only on Safari, it seems most other users have their cookies. The screen shot above is from Safari.

**Comment by covener** [comment]
Sorry, I'm not really following, and if there's no Set-Cookie on the wire the snippet in this repo can't possibly do anything.

**Comment by jtayler** [comment]
I can see the apache rules are working. Chrome seems fine for now, but Safari seems to have recently introduced a further security option called "Website tracking" and this option blocks these cookies by default.

I suspect there is no adjustment in apache that could prevent this, but you can see for yourself if you have access to Safari.

<img width="904" alt="Screen Shot 2020-12-20 at 5 03 27 PM" src="https://user-images.githubusercontent.com/1004984/102725515-49523380-42e5-11eb-8a62-866c0a2f3b6c.png">

**Comment by jtayler** [comment]
Do we think there is a cookie solution here or has Safari gone too far? Do we know the reason or if this can be detected at runtime I suppose and worked around somehow?

**Comment by covener** [comment]
The safari "ITP" features don't appear to relate to any header/cookie value so it's n/a for this repo.
